version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    image: fetal-app:x86
    ports:
      - "80:80"
      - "8081:8081"
    environment:
      - HOST=0.0.0.0
      - PORT=8081
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=fetal
      - TELEGRAM_BOT_TOKEN=8231116636:AAGT2sXLc6yanLcqO0QlpmA2bCLMIJFyFc8
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7.0
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
